var num1,num2,res;
num1=prompt("Digite um número");
num1=parseInt(num1);
num2=prompt("Digite outro número");
num2=parseInt(num2);
res=(num1==num2);
document.write("Números digitados:<br>num1: "+num1+"<br> num2: "+num2+"<hr>");
document.write("Igualdade: "+res+"<br>");
res=(num1===num2);
document.write("Idêntico: "+res+"<hr>");
res=(num1!=num2);
document.write("Não Igual: "+res+"<br>");
res=(num1!==num2);
document.write("Não idêntico: "+res+"<hr>");
res=(num1>num2);
document.write("Maior: "+res+"<br>");
res=(num1<num2);
document.write("Menor: "+res+"<hr>");
res=(num1>=num2);
document.write("Maior ou igual: "+res+"<br>");
res=(num1<=num2);
document.write("Menor ou igual: "+res+"<hr>");